shinyUI(
        tagList(
                uiInit(),
                conditionalPanel(
                        condition=(isDesktop),
                        uiDesktop()),
                conditionalPanel(
                        condition=(isMobile),
                        uiMobile())
        )
)
